### ISSUE TITLE
Adding some examples to the core documentation in vuetify vs ipyvuetify

### ISSUE THREAD

**Issue by joseberlines** [mariobuikhuizen/ipyvuetify#122]
at the end of the documentation page:
https://ipyvuetify.readthedocs.io/en/latest/usage.html#themes

there is a very nice explanation of how to "translate" vuetify to ipyvuetify stuff.

Well I think it would be really good to have a real example of every of the cases.

Why?
Because there are plenty of people like me that dont have a clue about JS and start directly experimenting with GUIS in python.
JS is gibberish for us and only via that explanation can be use the extensive vuetify js web site to look for things and try to ipy them.

note: "to ipy"  something is to transform whatever JS component in his ipy version for a notebook

**Comment by joseberlines** [comment]
For instance this example of vuetifyJS
(see: https://vuetifyjs.com/en/components/buttons/#floating)

<template>
  <v-row
    align="center"
    justify="space-around"
  >
    <v-btn depressed>
      Normal
    </v-btn>
    <v-btn
      depressed
      color="primary"
    >
      Primary
    </v-btn>
    <v-btn
      depressed
      color="error"
    >
      Error
    </v-btn>
    <v-btn
      depressed
      disabled
    >
      Disabled
    </v-btn>
  </v-row>
</template>

How should a coder only knowing python proceed in order to translate it following the rules of the documentation into ipyvuetify?

I am not looking for an answer to this example. With this example I am just showing the benefits of having just a little bit more documentation to help not JS coders.

**Comment by 12rambau** [comment]
By reading your example, I don't see a single line of JS, it's pure Html...
I think that every line you wrote can be "ipyed" by following carefully the documentation : 
```
toto = v.Row(
    align = 'center',
    justify = 'space-around',
    children= [
        v.Btn(
            depressed = True, 
            color = "primary", 
            children = [ #....
```

There are virtually an infinity of cases and combinations of vuetify elements, the documentation cannot reflect all of them.

> How should a coder only knowing python proceed in order to translate it following the rules of the documentation into ipyvuetify?  

by following the rules you started to read 😄 : https://ipyvuetify.readthedocs.io/en/latest/usage.html#summary

You can use the `python` and `ipyvuetify` tag in [Stack Overflow](https://stackoverflow.com) in order to receive help on specific translation. But you'll need to learn at least the structure of html before starting (no worries, it is very very straight forward).

**Comment by joseberlines** [comment]
Thanks a lot. Just closing the issue hence.
