### ISSUE TITLE
line-height property in textarea

### ISSUE THREAD

**Issue by guimillet** [mariobuikhuizen/ipyvuetify#125]
While defining font-family or font-size with the style_ property of a v.Textarea object works, defining line-height does not make any change.

I used v1.6.1 from conda-forge, in JupyterLab 2.2.9.

**Comment by mariobuikhuizen** [comment]
A Vuetify widget usually has some more internal HTML elements. The `style_` property is applied to the top level element. Because the font-* properties are not directly set in the sub elements, they are inherited by the sub element containing the text, the `line-height` property however, is set by the following CSS selector: `.vuetify-styles .v-text-field input `.

In the template version of ipyvuetify you can add CSS to override these styles.

**Comment by guimillet** [comment]
Thank you! However, this (`<style>.vuetify-styles .v-text-field textarea {line-height: ...}</style>`) redefines the property globally (for all textarea components).

For a local style, the only solution I found was to define a custom class and add a style section with an `!important` rule: ` <style>.myta textarea {line-height: ... !important}</style>`.

I tried [scoped and deep selectors](https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors) without success, whereas [it seems to work with vuetify](https://stackoverflow.com/a/65453035/2050118); could it be due to ipyvuetify.VuetifyTemplate?

**Comment by mariobuikhuizen** [comment]
Sorry, I looked at TextField instead of Textarea, so the selector that sets `line-height` is `.vuetify-styles .v-textarea textarea`

You can add a class of your own to make it unique for those text areas.
```html
<style>
  .vuetify-styles .v-textarea.myta textarea {
      line-height: ...
  }
</style>
```

**Comment by guimillet** [comment]
Thanks, that works too!

**Comment by guimillet** [comment]
I've found a shorter code than creating a VuetifyTemplate, by using `css = v.Html(tag='style', children=['.v-textarea.myta textarea {line-height: 1.3rem}'])` and including `css` in the display.
