### ISSUE TITLE
Include a radio button group in the examples collection.

### ISSUE THREAD

**Issue by joseberlines** [mariobuikhuizen/ipyvuetify#138]
Something in these lines will help:
```
parts =vue.RadioGroup(children=[vue.Radio(label='XX'),
                                             vue.Radio(label='YY'),
                                             vue.Radio(label='ZZ')])
#I dont know how can I access what the user clicks, hence I try to check all the properties of the radio button group as such:

out = widgets.Output()

def on_click_radio(widget, event, data):
    with out:
        out.clear_output()
        print("you have clicked", data)
        print("v_model is:", widget.v_model)
        print("value is", widget.value)
        print("active-class is", widget.active_class)
        widgetsKeys = widget.keys
        
         for key in widgetsKeys:
             print(f'{key}: ',eval(f'widget.{key}'))
         
        

parts.on_event("change",on_click_radio)

display(parts,out)
```

Appart from accessing data perhaps it would be nice to add a line as to how to access the value corresponding to that data

**Comment by guimillet** [comment]
As the [documentation explains it](https://ipyvuetify.readthedocs.io/en/latest/usage.html#reading-the-value):

> Reading the value
[...] In Vue this is done with the `v-model` directive, which is translated to Python as `v_model` ( note the ‘_’ instead of ‘-‘). **The `v_model` attribute has to be explicitly set when creating the widget.**

So, add `v_model=''` to the RadioGroup definition and then use the `v_model` property (or the event `data`)
```python
parts = vue.RadioGroup(v_model='', children=[vue.Radio(label='XX'),
                                             vue.Radio(label='YY'),
                                             vue.Radio(label='ZZ')])
```
```python
parts.v_model
```
> 2

I guess it's the same for all ipyvuetify widgets, including a [TextField input](https://github.com/mariobuikhuizen/ipyvuetify/issues/96).
