### ISSUE TITLE
How to call the button method btn.fire_event()

### ISSUE THREAD

**Issue by joseberlines** [mariobuikhuizen/ipyvuetify#210]
How are you supposed to call the fire_event method of a button?
The following gives error 

```
import ipyvuetify as v
b = v.Btn(children=['this btn'])
```
help(b)
indeed fire_event(self, event, data) exists but it is not called as such:

`b.fire_event('click', None)
`
ERROR: 99 def fire_event(self, event, data): --> 100 self._event_handlers_map[event](self, event, data)

KeyError: 'click'

This method is supposed to be used to call the click method in the button.

Can someone tell me how is the right way to call it?

thanks.

**Comment by mariobuikhuizen** [comment]
`fire_event` is primarily meant to be used internally by ipyvue. It calls the right event handler when an event is received from the front-end. This only happens when an event handler is assigned to an event, in this case `b.on_event('click', my_click_handler)`.

If you want to do the same thing programmatically as when the button is clicked, you can just call `my_click_handler` directly.

**Comment by joseberlines** [comment]
I guess in this case is not possible since the situation is the follwing:
btn_simple = vue.Btn(
    children = ['link'],
    href = 'http://www.google.de',
    target = '_blank'
)
btn_simple

there is no method to call. I have a bunch of buttons that would open particular urls and Depending on the situation I would like to fire some of them in one go. (note the url is a bit more complicated than that with parameters etc, only that for showing purposes I wirte simply google.com

**Comment by mariobuikhuizen** [comment]
Ah, right. There is currently no way to trigger an event like that in the front-end with ipyvuetivy or ipyvue (without using JS).

**Comment by joseberlines** [comment]
thanks a lot.
