### ISSUE TITLE
Styling issues with ipyleaflet and ipyvuetify

### ISSUE THREAD

**Issue by deeplook** [mariobuikhuizen/ipyvuetify#42]
I'm adventurous enough to combine ipyvuetify with ipyleaflet, and started putting maps in various Vue containers like Tabs and Carousels (I know, but hey, map kiosks are the next big thing ;).

I find some issues I feel must be related to competing styles or something maybe. In this case  specifically the map zoom buttons as well as the carousel sliding ones seem to work ok, but there is a gap at the bottom inside the carousel. So it looks like something is slightly wrong with the way ipyvuetify creates this content inside the carousel. I cannot see any JS errors in the web console. I'm attaching a simple example screenshot and the code for easier reproducibility. (This was created in a Jupyter classic notebook.)

```python
import ipyleaflet as ll
import ipyvuetify as v

print(f"ipyleafet {ll.__version__}")
print(f"ipyvuetify {v.__version__}")

maps = [ll.Map(center=[0, 0], zoom=zoom) for zoom in range(1, 6)]
v.Carousel(children=[v.CarouselItem(children=[m]) for m in maps])
```
<img width="899" alt="Screenshot 2019-12-03 at 12 06 00" src="https://user-images.githubusercontent.com/1001778/70046477-6e82df80-15c6-11ea-91a3-4e127b21b47e.png">

**Comment by mariobuikhuizen** [comment]
Thanks for reporting this issue. 

The ipyleaflet map has a fixed height so it will not fill the height of the parent element. This can be changed by setting the height to 100% in the layout traitlet of the map.

This only works since version 1.0.1 of ipyvue, so be sure to update this dependency.

```python
import ipyleaflet as ll
import ipyvuetify as v

print(f"ipyleafet {ll.__version__}")
print(f"ipyvuetify {v.__version__}")
print(f"ipyvue {__import__('ipyvue').__version__}")

maps = [ll.Map(center=[0, 0], zoom=zoom, layout={'height': '100%'}) for zoom in range(1, 6)]
v.Carousel(children=[v.CarouselItem(children=[m]) for m in maps])
```
<img width="1015" alt="Schermafbeelding 2019-12-04 om 15 07 29" src="https://user-images.githubusercontent.com/46192475/70149176-e07f2580-16a7-11ea-852c-316b3f6f4424.png">

Best wishes on your adventures! :-)

**Comment by mariobuikhuizen** [comment]
It looks great btw! :-) Props to you and the ipyleaflet devs.
![map](https://user-images.githubusercontent.com/46192475/70150452-51274180-16aa-11ea-9fb0-ff20ca2ddf4f.gif)

**Comment by deeplook** [comment]
Thanks!!
